import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import { expect } from "chai";
import BN from "bn.js";

// ---------------------------------------------------------------------------
// IDL Types (generated by `anchor build` — typed manually for scaffold)
// ---------------------------------------------------------------------------

// These type stubs will be replaced by auto-generated types from
// `target/types/ciphervault_core.ts` after the first `anchor build`.
type CiphervaultCore = any;
type CollateralVault = any;

// ---------------------------------------------------------------------------
// Test Constants
// ---------------------------------------------------------------------------

const PROTOCOL_SEED = Buffer.from("protocol");
const VAULT_SEED = Buffer.from("vault");
const ORDER_SEED = Buffer.from("order");
const SETTLEMENT_SEED = Buffer.from("settlement");
const VAULT_REGISTRY_SEED = Buffer.from("vault_registry");
const COLLATERAL_SEED = Buffer.from("collateral");

/** ChainAsset enum values matching the on-chain Rust enum */
const ChainAsset = {
  BtcNative: 0,
  EthNative: 1,
  SolNative: 2,
  Usdc: 3,
  TokenizedTBill: 4,
  TokenizedRealEstate: 5,
  TokenizedGold: 6,
} as const;

/** OrderDirection enum values */
const OrderDirection = {
  Long: 0,
  Short: 1,
} as const;

// ---------------------------------------------------------------------------
// PDA Helpers
// ---------------------------------------------------------------------------

function findProtocolPda(programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([PROTOCOL_SEED], programId);
}

function findVaultPda(
  programId: PublicKey,
  trader: PublicKey,
  chainAsset: number
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [VAULT_SEED, trader.toBuffer(), Buffer.from([chainAsset])],
    programId
  );
}

function findOrderPda(
  programId: PublicKey,
  trader: PublicKey,
  orderIndex: BN
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [ORDER_SEED, trader.toBuffer(), orderIndex.toArrayLike(Buffer, "le", 8)],
    programId
  );
}

function findSettlementPda(
  programId: PublicKey,
  buyOrderId: BN,
  sellOrderId: BN
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [
      SETTLEMENT_SEED,
      buyOrderId.toArrayLike(Buffer, "le", 8),
      sellOrderId.toArrayLike(Buffer, "le", 8),
    ],
    programId
  );
}

function findVaultRegistryPda(programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([VAULT_REGISTRY_SEED], programId);
}

function findCollateralAccountPda(
  programId: PublicKey,
  trader: PublicKey,
  chainAsset: number
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [COLLATERAL_SEED, trader.toBuffer(), Buffer.from([chainAsset])],
    programId
  );
}

// ---------------------------------------------------------------------------
// CipherVault Core Tests
// ---------------------------------------------------------------------------

describe("ciphervault-core", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // Program references — will use actual IDL after first build
  // const coreProgram = anchor.workspace.CiphervaultCore as Program<CiphervaultCore>;
  const authority = provider.wallet;
  const trader = Keypair.generate();

  // Protocol parameters
  const maxLeverageBps = 50_000; // 5x
  const settlementWindowSlots = new BN(100);
  const feeRateBps = 30; // 0.30%

  before(async () => {
    // Fund the test trader account
    const airdropSig = await provider.connection.requestAirdrop(
      trader.publicKey,
      2 * LAMPORTS_PER_SOL
    );
    const latestBlockhash = await provider.connection.getLatestBlockhash();
    await provider.connection.confirmTransaction({
      signature: airdropSig,
      ...latestBlockhash,
    });
  });

  describe("initialize", () => {
    it("initializes the protocol state with correct parameters", async () => {
      const [protocolPda] = findProtocolPda(coreProgram.programId);

      await coreProgram.methods
        .initialize(maxLeverageBps, settlementWindowSlots, feeRateBps)
        .accounts({
          protocol: protocolPda,
          authority: authority.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      const protocolAccount = await coreProgram.account.protocol.fetch(protocolPda);
      expect(protocolAccount.authority.toBase58()).to.equal(authority.publicKey.toBase58());
      expect(protocolAccount.maxLeverageBps).to.equal(maxLeverageBps);
      expect(protocolAccount.settlementWindowSlots.toNumber()).to.equal(100);
      expect(protocolAccount.feeRateBps).to.equal(feeRateBps);
      expect(protocolAccount.isFrozen).to.be.false;
      expect(protocolAccount.totalVaults.toNumber()).to.equal(0);
      expect(protocolAccount.totalOrders.toNumber()).to.equal(0);
      expect(protocolAccount.totalSettlements.toNumber()).to.equal(0);
    });
  });

  describe("deposit_collateral", () => {
    it("records a BTC collateral deposit with correct accounting", async () => {
      // const [protocolPda] = findProtocolPda(coreProgram.programId);
      // const [vaultPda] = findVaultPda(
      //   coreProgram.programId,
      //   trader.publicKey,
      //   ChainAsset.BtcNative
      // );
      // const dwalletId = new Uint8Array(32).fill(1);
      //
      // await coreProgram.methods
      //   .depositCollateral(
      //     { btcNative: {} },  // ChainAsset enum variant
      //     new BN(100_000_000), // 1 BTC in satoshis
      //     Array.from(dwalletId)
      //   )
      //   .accounts({
      //     protocol: protocolPda,
      //     collateralVault: vaultPda,
      //     trader: trader.publicKey,
      //     systemProgram: SystemProgram.programId,
      //   })
      //   .signers([trader])
      //   .rpc();
      //
      // const vaultAccount = await coreProgram.account.collateralVault.fetch(vaultPda);
      // expect(vaultAccount.owner.toBase58()).to.equal(trader.publicKey.toBase58());
      // expect(vaultAccount.depositedAmount.toNumber()).to.equal(100_000_000);
      // expect(vaultAccount.chainAsset).to.deep.equal({ btcNative: {} });

      console.log("⏳ deposit_collateral test: awaiting IDL generation");
    });

    it("rejects deposit when protocol is frozen", async () => {
      // Test that CipherVaultError::VaultFrozen is returned when
      // the protocol.is_frozen flag is set to true.
      console.log("⏳ frozen deposit test: awaiting IDL generation");
    });

    it("rejects deposit with zero amount", async () => {
      // Test that CipherVaultError::InsufficientCollateral is returned
      // when amount = 0.
      console.log("⏳ zero deposit test: awaiting IDL generation");
    });
  });

  describe("withdraw_collateral", () => {
    it("withdraws collateral and updates vault balance", async () => {
      // const [vaultPda] = findVaultPda(
      //   coreProgram.programId,
      //   trader.publicKey,
      //   ChainAsset.BtcNative
      // );
      //
      // await coreProgram.methods
      //   .withdrawCollateral(new BN(50_000_000)) // 0.5 BTC
      //   .accounts({
      //     protocol: protocolPda,
      //     collateralVault: vaultPda,
      //     trader: trader.publicKey,
      //   })
      //   .signers([trader])
      //   .rpc();
      //
      // const vaultAccount = await coreProgram.account.collateralVault.fetch(vaultPda);
      // expect(vaultAccount.depositedAmount.toNumber()).to.equal(50_000_000);

      console.log("⏳ withdraw test: awaiting IDL generation");
    });

    it("rejects withdrawal from non-owner", async () => {
      // Test that CipherVaultError::Unauthorized is returned
      console.log("⏳ unauthorized withdrawal test: awaiting IDL generation");
    });

    it("rejects withdrawal that breaches health factor", async () => {
      // Test that CipherVaultError::InvalidHealthFactor is returned
      // when remaining collateral < 150% of borrowed
      console.log("⏳ health factor breach test: awaiting IDL generation");
    });
  });

  describe("place_order", () => {
    it("places an encrypted long order", async () => {
      // const mockEncryptedSize = Buffer.alloc(32, 0xAA);
      // const mockEncryptedPrice = Buffer.alloc(32, 0xBB);
      //
      // const [protocolPda] = findProtocolPda(coreProgram.programId);
      // const [orderPda] = findOrderPda(
      //   coreProgram.programId,
      //   trader.publicKey,
      //   new BN(0) // first order
      // );
      //
      // await coreProgram.methods
      //   .placeOrder(
      //     mockEncryptedSize,
      //     mockEncryptedPrice,
      //     { long: {} }
      //   )
      //   .accounts({
      //     protocol: protocolPda,
      //     encryptedOrder: orderPda,
      //     trader: trader.publicKey,
      //     systemProgram: SystemProgram.programId,
      //   })
      //   .signers([trader])
      //   .rpc();
      //
      // const orderAccount = await coreProgram.account.encryptedOrder.fetch(orderPda);
      // expect(orderAccount.orderId.toNumber()).to.equal(0);
      // expect(orderAccount.direction).to.deep.equal({ long: {} });
      // expect(orderAccount.isFilled).to.be.false;
      // expect(orderAccount.isCancelled).to.be.false;

      console.log("⏳ place_order test: awaiting IDL generation");
    });

    it("rejects order with empty encrypted data", async () => {
      // Test that CipherVaultError::EncryptionFailure is returned
      console.log("⏳ empty encryption test: awaiting IDL generation");
    });
  });

  describe("settle_trade", () => {
    it("settles a matched trade between buyer and seller", async () => {
      // Requires two orders (long + short) to be placed first,
      // then a settlement instruction referencing both.
      //
      // const [settlementPda] = findSettlementPda(
      //   coreProgram.programId,
      //   new BN(0), // buy order ID
      //   new BN(1), // sell order ID
      // );
      //
      // await coreProgram.methods
      //   .settleTrade(
      //     new BN(1_000_000),  // settled size
      //     new BN(60_000_000), // settled price
      //   )
      //   .accounts({
      //     protocol: protocolPda,
      //     buyOrder: buyOrderPda,
      //     sellOrder: sellOrderPda,
      //     tradeSettlement: settlementPda,
      //     settler: authority.publicKey,
      //     systemProgram: SystemProgram.programId,
      //   })
      //   .rpc();
      //
      // const settlement = await coreProgram.account.tradeSettlement.fetch(settlementPda);
      // expect(settlement.settledSize.toNumber()).to.equal(1_000_000);
      // expect(settlement.settledPrice.toNumber()).to.equal(60_000_000);

      console.log("⏳ settle_trade test: awaiting IDL generation");
    });

    it("rejects settlement with mismatched order directions", async () => {
      // Test that CipherVaultError::InvalidSettlement is returned
      console.log("⏳ mismatched directions test: awaiting IDL generation");
    });
  });
});

// ---------------------------------------------------------------------------
// Collateral Vault Tests
// ---------------------------------------------------------------------------

describe("collateral-vault", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const authority = provider.wallet;
  const trader = Keypair.generate();

  before(async () => {
    const airdropSig = await provider.connection.requestAirdrop(
      trader.publicKey,
      2 * LAMPORTS_PER_SOL
    );
    const latestBlockhash = await provider.connection.getLatestBlockhash();
    await provider.connection.confirmTransaction({
      signature: airdropSig,
      ...latestBlockhash,
    });
  });

  describe("initialize_vault", () => {
    it("initializes the vault registry", async () => {
      console.log("⏳ initialize_vault test: awaiting IDL generation");
    });
  });

  describe("register_dwallet", () => {
    it("registers a BTC dWallet for a trader", async () => {
      // const dwalletId = new Uint8Array(32).fill(0xAB);
      // const dwalletPublicKey = new Uint8Array(33).fill(0xCD);
      //
      // const [registryPda] = findVaultRegistryPda(vaultProgram.programId);
      // const [accountPda] = findCollateralAccountPda(
      //   vaultProgram.programId,
      //   trader.publicKey,
      //   ChainAsset.BtcNative
      // );
      //
      // await vaultProgram.methods
      //   .registerDwallet(
      //     { btcNative: {} },
      //     Array.from(dwalletId),
      //     Array.from(dwalletPublicKey),
      //   )
      //   .accounts({
      //     vaultRegistry: registryPda,
      //     collateralAccount: accountPda,
      //     trader: trader.publicKey,
      //     systemProgram: SystemProgram.programId,
      //   })
      //   .signers([trader])
      //   .rpc();
      //
      // const account = await vaultProgram.account.collateralAccount.fetch(accountPda);
      // expect(account.isDwalletRegistered).to.be.true;
      // expect(account.owner.toBase58()).to.equal(trader.publicKey.toBase58());

      console.log("⏳ register_dwallet test: awaiting IDL generation");
    });

    it("rejects duplicate dWallet registration", async () => {
      // Test that CollateralVaultError::DwalletAlreadyRegistered is returned
      console.log("⏳ duplicate registration test: awaiting IDL generation");
    });
  });

  describe("record_deposit", () => {
    it("records a deposit with oracle price conversion", async () => {
      console.log("⏳ record_deposit test: awaiting IDL generation");
    });

    it("rejects deposit without registered dWallet", async () => {
      console.log("⏳ unregistered dWallet deposit test: awaiting IDL generation");
    });
  });

  describe("record_withdrawal", () => {
    it("records a withdrawal and enforces health factor", async () => {
      console.log("⏳ record_withdrawal test: awaiting IDL generation");
    });
  });

  describe("check_health", () => {
    it("emits correct health factor for a collateralized position", async () => {
      // This test verifies the HealthChecked event is emitted with correct values.
      // Since check_health is read-only, we verify via event parsing.
      console.log("⏳ check_health test: awaiting IDL generation");
    });

    it("flags under-collateralized positions as liquidatable", async () => {
      console.log("⏳ liquidatable position test: awaiting IDL generation");
    });
  });
});
