import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import { expect } from "chai";

// The IDL type will be generated by `anchor build`. We use `any` for Phase 1
// since the IDL isn't imported at compile time.
type CollateralVault = any;

describe("collateral-vault", () => {
  // Configure the cluster
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace
    .CollateralVault as Program<CollateralVault>;

  // Test fixtures
  const user = provider.wallet;
  const oracleKeypair = Keypair.generate();

  // Generate a deterministic dWallet ID for testing
  const testDwalletId = Array.from(
    Keypair.generate().publicKey.toBytes()
  ) as number[];

  // PDA derivation helper (mirrors on-chain seeds exactly)
  function deriveVaultPda(owner: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), owner.toBuffer()],
      program.programId
    );
  }

  const [vaultPda, vaultBump] = deriveVaultPda(user.publicKey);

  // ---------------------------------------------------------------------------
  // Helper: Initialize vault with default params
  // ---------------------------------------------------------------------------
  async function initVault(
    ltv: number = 7000,
    liqThreshold: number = 8500
  ): Promise<string> {
    return program.methods
      .initializeVault(ltv, liqThreshold)
      .accounts({
        vault: vaultPda,
        user: user.publicKey,
        oracleAuthority: oracleKeypair.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
  }

  // ---------------------------------------------------------------------------
  // Helper: Register a dWallet
  // ---------------------------------------------------------------------------
  async function registerDwallet(
    dwalletId: number[] = testDwalletId,
    chain: number = 0,
    asset: number = 0
  ): Promise<string> {
    return program.methods
      .registerDwallet(dwalletId, chain, asset)
      .accounts({
        vault: vaultPda,
        user: user.publicKey,
      })
      .rpc();
  }

  // ---------------------------------------------------------------------------
  // Helper: Record a deposit (requires oracle signer)
  // ---------------------------------------------------------------------------
  async function recordDeposit(
    dwalletId: number[],
    rawAmount: BN,
    usdPrice: BN
  ): Promise<string> {
    return program.methods
      .recordDeposit(dwalletId, rawAmount, usdPrice)
      .accounts({
        vault: vaultPda,
        oracleAuthority: oracleKeypair.publicKey,
      })
      .signers([oracleKeypair])
      .rpc();
  }

  // ---------------------------------------------------------------------------
  // Test 1: Initializes vault with correct parameters
  // ---------------------------------------------------------------------------
  it("initializes vault with correct parameters", async () => {
    const txSig = await initVault(7000, 8500);
    expect(txSig).to.be.a("string");

    const vault = await program.account.vaultAccount.fetch(vaultPda);

    expect(vault.owner.toBase58()).to.equal(user.publicKey.toBase58());
    expect(vault.oracleAuthority.toBase58()).to.equal(
      oracleKeypair.publicKey.toBase58()
    );
    expect(vault.ltvBps).to.equal(7000);
    expect(vault.liquidationThresholdBps).to.equal(8500);
    expect((vault.totalCollateralUsd as BN).toNumber()).to.equal(0);
    expect((vault.usedCreditUsd as BN).toNumber()).to.equal(0);
    expect(vault.isFrozen).to.equal(false);
    expect(vault.numPositions).to.equal(0);
    // Fixed arrays always have 8 entries; numPositions tracks active count
    expect((vault.dwalletIds as any[]).length).to.equal(8);
    expect((vault.positions as any[]).length).to.equal(8);
  });

  // ---------------------------------------------------------------------------
  // Test 2: Registers a dWallet successfully
  // ---------------------------------------------------------------------------
  it("registers a dWallet successfully", async () => {
    const txSig = await registerDwallet(testDwalletId, 0, 0);
    expect(txSig).to.be.a("string");

    const vault = await program.account.vaultAccount.fetch(vaultPda);

    // Check numPositions incremented
    expect(vault.numPositions).to.equal(1);

    // Check dWallet ID was stored in slot 0
    const storedIds = vault.dwalletIds as number[][];
    expect(storedIds[0]).to.deep.equal(testDwalletId);

    // Check position was created with zero amount in slot 0
    const positions = vault.positions as any[];
    expect(positions[0].chain).to.equal(0);
    expect(positions[0].asset).to.equal(0);
    expect((positions[0].rawAmount as BN).toNumber()).to.equal(0);
    expect((positions[0].usdValue as BN).toNumber()).to.equal(0);
  });

  // ---------------------------------------------------------------------------
  // Test 3: Records a deposit and updates collateral
  // ---------------------------------------------------------------------------
  it("records a deposit and updates collateral", async () => {
    // 1 BTC = 100,000,000 sats, price = $65,000.000000
    const rawAmount = new BN(100_000_000);
    const usdPrice = new BN(65_000_000_000); // 65000 * 1_000_000

    const txSig = await recordDeposit(testDwalletId, rawAmount, usdPrice);
    expect(txSig).to.be.a("string");

    const vault = await program.account.vaultAccount.fetch(vaultPda);

    // Expected USD value: (100_000_000 * 65_000_000_000) / 1_000_000
    // = 6_500_000_000_000_000 / 1_000_000 = 6_500_000_000_000
    // Wait — let's recalculate:
    // raw_amount = 100_000_000
    // usd_price_6dec = 65_000_000_000
    // deposit USD = 100_000_000 * 65_000_000_000 / 1_000_000
    //             = 6_500_000_000_000_000 / 1_000_000
    //             = 6_500_000_000_000
    //
    // But this is the TOTAL position value (all raw_amount * price / 1e6).
    // For 1 BTC at $65k with 6 decimal precision:
    // position.usd_value = 100_000_000 * 65_000_000_000 / 1_000_000
    //                    = 6_500_000_000_000

    const expectedUsd = new BN("6500000000000");
    expect(
      (vault.totalCollateralUsd as BN).toString()
    ).to.equal(expectedUsd.toString());

    // Verify position raw amount
    const positions = vault.positions as any[];
    expect((positions[0].rawAmount as BN).toNumber()).to.equal(100_000_000);
    expect(
      (positions[0].usdValue as BN).toString()
    ).to.equal(expectedUsd.toString());
  });

  // ---------------------------------------------------------------------------
  // Test 4: check_health returns MAX when no credit used
  // ---------------------------------------------------------------------------
  it("check_health returns MAX when no credit used", async () => {
    // The vault has collateral but usedCreditUsd = 0, so health = u64::MAX
    // We need to use the simulate or view approach since check_health returns a value.

    // First verify via account state
    const vault = await program.account.vaultAccount.fetch(vaultPda);
    expect((vault.usedCreditUsd as BN).toNumber()).to.equal(0);

    // Call check_health via simulate to get the return value
    // In Anchor, we can use .simulate() or just verify the event emission
    const txSig = await program.methods
      .checkHealth()
      .accounts({
        vault: vaultPda,
      })
      .rpc();

    expect(txSig).to.be.a("string");

    // The function emits HealthChecked with health_bps = u64::MAX when
    // used_credit_usd == 0. We verify this by checking the vault state
    // hasn't changed (it's a read-only operation) and the tx succeeded.
    // The return value u64::MAX is emitted in the event.
    const vaultAfter = await program.account.vaultAccount.fetch(vaultPda);
    expect((vaultAfter.usedCreditUsd as BN).toNumber()).to.equal(0);
  });

  // ---------------------------------------------------------------------------
  // Test 5: Rejects withdrawal that breaches liquidation threshold
  // ---------------------------------------------------------------------------
  it("rejects withdrawal that breaches liquidation threshold", async () => {
    // Simulate outstanding credit by calling update_credit
    // Current total_collateral_usd ~ 6_500_000_000_000 (6.5T in 6-dec USD)
    // Set used_credit_usd high enough that withdrawing all collateral would breach threshold
    //
    // Liquidation threshold = 8500 bps (85%)
    // If used_credit = 5_000_000_000_000, then:
    //   health = 6_500_000_000_000 * 10_000 / 5_000_000_000_000 = 13_000 bps (130%)
    //   That's above 8500, so the current state is healthy.
    //
    // If we try to withdraw nearly everything:
    //   projected_total ≈ 0
    //   projected_health = 0 * 10_000 / 5_000_000_000_000 = 0 < 8500
    //   Should fail with InsufficientCollateral

    const usedCredit = new BN("5000000000000");
    await program.methods
      .updateCredit(usedCredit)
      .accounts({
        vault: vaultPda,
        user: user.publicKey,
      })
      .rpc();

    // Verify credit was set
    const vault = await program.account.vaultAccount.fetch(vaultPda);
    expect((vault.usedCreditUsd as BN).toString()).to.equal(
      usedCredit.toString()
    );

    // Now attempt to withdraw 90_000_000 sats (0.9 BTC) — would remove most collateral
    const withdrawAmount = new BN(90_000_000);
    const usdPrice = new BN(65_000_000_000);

    try {
      await program.methods
        .recordWithdrawal(testDwalletId, withdrawAmount, usdPrice)
        .accounts({
          vault: vaultPda,
          oracleAuthority: oracleKeypair.publicKey,
        })
        .signers([oracleKeypair])
        .rpc();

      // If we get here, the test failed
      expect.fail("Expected InsufficientCollateral error");
    } catch (err: any) {
      // Anchor wraps the error — check for our custom error
      expect(err.toString()).to.include("InsufficientCollateral");
    }
  });

  // ---------------------------------------------------------------------------
  // Test 6: Rejects duplicate dWallet registration
  // ---------------------------------------------------------------------------
  it("rejects duplicate dWallet registration", async () => {
    // testDwalletId was already registered in test 2
    try {
      await registerDwallet(testDwalletId, 0, 0);
      expect.fail("Expected DWalletAlreadyRegistered error");
    } catch (err: any) {
      expect(err.toString()).to.include("DWalletAlreadyRegistered");
    }
  });

  // ---------------------------------------------------------------------------
  // Additional edge case tests
  // ---------------------------------------------------------------------------

  it("rejects LTV >= liquidation threshold", async () => {
    // Create a new user to test initialization validation
    const newUser = Keypair.generate();

    // Airdrop to the new user for rent
    const airdropSig = await provider.connection.requestAirdrop(
      newUser.publicKey,
      2 * anchor.web3.LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(airdropSig);

    const [newVaultPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), newUser.publicKey.toBuffer()],
      program.programId
    );

    try {
      await program.methods
        .initializeVault(9000, 8500) // LTV > liq threshold → invalid
        .accounts({
          vault: newVaultPda,
          user: newUser.publicKey,
          oracleAuthority: oracleKeypair.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([newUser])
        .rpc();

      expect.fail("Expected LtvExceedsLiquidationThreshold error");
    } catch (err: any) {
      expect(err.toString()).to.include("LtvExceedsLiquidationThreshold");
    }
  });

  it("rejects unauthorized oracle deposits", async () => {
    const fakeOracle = Keypair.generate();

    try {
      await program.methods
        .recordDeposit(testDwalletId, new BN(50_000_000), new BN(65_000_000_000))
        .accounts({
          vault: vaultPda,
          oracleAuthority: fakeOracle.publicKey,
        })
        .signers([fakeOracle])
        .rpc();

      expect.fail("Expected UnauthorizedOracle error");
    } catch (err: any) {
      expect(err.toString()).to.include("UnauthorizedOracle");
    }
  });
});
